module.exports = {
  version: '0.2',
  language: 'en',
  words: [
    // general
    'nuxt',
    'nuxtjs',
    'vuetify',
    'vuepress',
    'jscoverage',
    'toastify',
    // projects
    'noindex',
    'inbug',
    'anothr',
  ],
  ignoreWords: ['emretepedev', 'emre', 'tepe', 'osmangazi', 'bixos'],
  ignorePaths: ['yarn.lock', '.git', '.vscode'],
  allowCompoundWords: true,
  dictionaries: [
    'vue',
    'javascript',
    'typescript',
    'css',
    'scss',
    'html',
    'html-symbol-entities',
    'npm',
    'node',
    'fullstack',
    'fonts',
    'filetypes',
    'softwareTerms',
    'dockerfile',
    'markdown',
    'xml',
    'yaml',
    'bash',
    'powershell',
    'cpp',
    'c',
    'json',
    'jsonc',
    'plaintext',
    'aws',
    'public-licenses',
    'cryptocurrencies',
    'companies',
    'misc',
    'en-gb',
    'lorem-ipsum',
  ],
}
