module.exports = {
  version: '0.2',

  language: 'en',

  words: [
    // general
    'nuxt',
    'nuxi',
    'nuxtjs',
    'vuetify',
    'vuepress',
    'toastify',
    'jscoverage',
    'noindex',
    'inbug',
    'anothr',
    'mythril',
    'nocompatible',
    'vmid',
    'vtoastify',
    'pinia',
    'vueuse',
    'toastification',
  ],

  ignoreWords: ['emretepedev', 'emre', 'tepe', 'osmangazi', 'bixos'],

  ignorePaths: [
    'yarn.lock',
    '.git',
    '.vscode',
    '.husky',
    '*.webp',
    '*.svg',
    '*.jpg',
    '*.jpeg',
    '*.png',
  ],

  allowCompoundWords: true,

  dictionaries: [
    'vue',
    'javascript',
    'typescript',
    'css',
    'scss',
    'html',
    'html-symbol-entities',
    'npm',
    'node',
    'fullstack',
    'fonts',
    'filetypes',
    'softwareTerms',
    'dockerfile',
    'markdown',
    'xml',
    'yaml',
    'bash',
    'powershell',
    'cpp',
    'c',
    'json',
    'jsonc',
    'plaintext',
    'aws',
    'public-licenses',
    'cryptocurrencies',
    'companies',
    'misc',
    'en-gb',
    'lorem-ipsum',
  ],
}
