module.exports = {
  version: '0.2',
  language: 'en',
  words: [
    'nuxt',
    'nuxtjs',
    'vuetify',
    'vuepress',
    'jscoverage',
    'purgecss',
    'toastify',
    'tailwindcss',
    'pageclip',
    'workdir',
    'changefreq',
    'noindex',
    'inbug',
  ],
  flagWords: [],
  ignoreWords: ['emretepedev', 'emre', 'tepe', 'osmangazi', 'bixos'],
  ignorePaths: ['yarn.lock'],
  allowCompoundWords: true,
  import: [],
  dictionaries: [
    'vue',
    'javascript',
    'typescript',
    'css',
    'html',
    'html-symbol-entities',
    'npm',
    'node',
    'fullstack',
    'fonts',
    'filetypes',
    'softwareTerms',
    'bash',
    'powershell',
    'cpp',
    'aws',
    'public-licenses',
    'cryptocurrencies',
  ],
}
