name: Fetch recent contributions count

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

env:
  NODE_ENV: ${{ secrets.NODE_ENV }}
  SPA_NAME: ${{ secrets.SPA_NAME }}
  SPA_ORIGIN: ${{ secrets.SPA_ORIGIN }}
  SPA_URL: ${{ secrets.SPA_URL }}
  SPA_PATH: ${{ secrets.SPA_PATH }}
  GH_USERNAME: ${{ secrets.GH_USERNAME }}
  GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
  GOOGLE_RECAPTCHA_V2_SITE_KEY: ${{ secrets.GOOGLE_RECAPTCHA_V2_SITE_KEY }}
  GOOGLE_RECAPTCHA_V3_SITE_KEY: ${{ secrets.GOOGLE_RECAPTCHA_V3_SITE_KEY }}
  GOOGLE_TAG_MANAGER_ID: ${{ secrets.GOOGLE_TAG_MANAGER_ID }}
  GOOGLE_ANALYTICS_4_ID: ${{ secrets.GOOGLE_ANALYTICS_4_ID }}
  PAGECLIP_ACTION_URL: ${{ secrets.PAGECLIP_ACTION_URL }}
  OWNER_ADDRESS: ${{ secrets.OWNER_ADDRESS }}
  TX_CONFIRMATION_BLOCKS: ${{ secrets.TX_CONFIRMATION_BLOCKS }}
  REPOSITORY_URL: ${{ secrets.REPOSITORY_URL }}
  GUESTBOOK_CONTRACT_ADDRESS: ${{ secrets.GUESTBOOK_CONTRACT_ADDRESS }}
  GUESTBOOK_CONTRACT_CHAIN_ID: ${{ secrets.GUESTBOOK_CONTRACT_CHAIN_ID }}
  GUESTBOOK_CONTRACT_CHAIN_NAME: ${{ secrets.GUESTBOOK_CONTRACT_CHAIN_NAME }}
  TEST_WEBSITE: ${{ secrets.TEST_WEBSITE }}
  LIVE: ${{ secrets.LIVE }}

jobs:
  fetch-recent-contributions-count:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-22.04]
        node: [18]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies with dev deps
        run: yarn install --production=false

      - name: Fetch recent contributions count
        run: yarn fetch

      - name: Build
        run: yarn build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.output/public
          publish_branch: gh-pages
